name: Generate site on merge 
on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Build site
        run: |
          chmod +x ./build.sh
          ./build.sh
        env:
          REPO_CONTEXT: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4

